### ISSUE TITLE
Vertical Interpolation DimensionalityError observed in migrating from Python 3.7.10 to Python 3.8.6

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METcalcpy#180]
*Replace italics below with details for this issue.*

## Describe the Problem ##
running the vertical interpolation example for the height_from_pressure_tcrmw.sh script, which exercises the vertical_interp.py module produces the following error when using Python 3.8, with any version of pint and metpy (ie pint 0.17, 0.18, or 0.19 and metpy v 1.1, 1.3):

raise DimensionalityError(self._units, "dimensionless")
pint.errors.DimensionalityError: Cannot convert from 'second ** 2 / meter' to 'dimensionless'

This was previously successfully creating an output netcdf file with interpolated levels using Python 3.7.10 and pint 0.17, metpy 1.1.

### Expected Behavior ###
This should successfully create an output netCDF file with the vertically interpolated heights. 

### Environment ###
Describe your runtime environment:
*1. Machine: (e.g. HPC name, Linux Workstation, Mac Laptop)* Linux
*2. OS: (e.g. RedHat Linux, MacOS)* Debian
*3. Software version number(s)* Python 3.8.6 with combinations of pint: 0.17, 0.18, 0.19 and metpy 1.1, 1.3

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Working on 'seneca', clone METcalcpy development branch and set up PYTHONPATH
*2. set up appropriate directory paths in the height_from_pressure_tcrmw.sh script as follows, except direct the output to your own directory where you have read/write permissions:
export DATA_DIR=/d1/projects/METcalcpy/METcalcpy_Data/Vert_Interp
python ../metcalcpy/vertical_interp.py \
    --datadir $DATA_DIR \
    --input $DATA_DIR/tc_rmw_dev_test_out.nc \
    --config height_from_pressure_tcrmw.yaml \
    --output /d1/personal/mwin/output/tc_rmw_dev_test_vertical_interp.nc \
#--debug
*3. activate the metcalcpy_py38_6 conda environment on 'seneca': /home/met_test/.conda/envs/metcalcpy_py38_6
*4. invoke the height_from_pressure_tcrmw.sh script
*5. You will see output like the following:
Traceback (most recent call last):
  File "/d1/personal/mwin/feature_153_deprecations/METcalcpy/examples/../metcalcpy/vertical_interp.py", line 656, in <module>
    layer_height = height_from_pressure(config,
  File "/d1/personal/mwin/feature_153_deprecations/METcalcpy/examples/../metcalcpy/vertical_interp.py", line 394, in height_from_pressure
    surface_height + layer_thickness.loc[{lev_dim: pressure_coord[0]}],
  File "/d1/personal/mwin/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/core/_typed_ops.py", line 206, in __add__
    return self._binary_op(other, operator.add)
  File "/d1/personal/mwin/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/core/dataarray.py", line 3098, in _binary_op
    f(self.variable, other_variable)
  File "/d1/personal/mwin/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/core/_typed_ops.py", line 396, in __add__
    return self._binary_op(other, operator.add)
  File "/d1/personal/mwin/miniconda3/envs/py39/lib/python3.9/site-packages/xarray/core/variable.py", line 2467, in _binary_op
    f(self_data, other_data) if not reflexive else f(other_data, self_data)
  File "/d1/personal/mwin/miniconda3/envs/py39/lib/python3.9/site-packages/pint/quantity.py", line 1154, in __add__
    return self._add_sub(other, operator.add)
  File "/d1/personal/mwin/miniconda3/envs/py39/lib/python3.9/site-packages/pint/quantity.py", line 139, in wrapped
    return f(self, *args, **kwargs)
  File "/d1/personal/mwin/miniconda3/envs/py39/lib/python3.9/site-packages/pint/quantity.py", line 1052, in _add_sub
    raise DimensionalityError(self._units, "dimensionless")
pint.errors.DimensionalityError: Cannot convert from 'second ** 2 / meter' to 'dimensionless'
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

**NOTE:
on 'eyewall', using the /home/met_test/.conda/envs/cloned_metplotpy_vert_interp conda environment, this script runs successfully.**

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2792541

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Organization** level **Project** for support of the current coordinated release
- [ ] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by bikegeek** [comment]
The error occurs in this line in the vertical_interp.py script:
layer_height.loc[{lev_dim: pressure_coord[0]}] \
        = xr.where(surface_mask.loc[{lev_dim: pressure_coord[0]}],
            surface_height + layer_thickness.loc[{lev_dim: pressure_coord[0]}],
            np.nan)

In the debugger, the surface_height is in units of meters and the layer_thickness.loc[{lev_dim: pressure_coord[0]}] is also in meters.  

When attempting to perform the addition in the debugger console:
     surface_height + layer_thickness.loc[{lev_dim: pressure_coord[0]}]

the error is reproduced.  

Upon closer inspection between the two versions of Python (3.7 vs 3.8) it appears that in xarray 0.20.2 (used with the Python 3.7 conda env) vs xarray 2022.6.0 (used by the Python 3.8 conda env), the creation of the resulting surface_height in the code at line 280: 

     surface_height = xr.DataArray(
        surface_geopotential / constants.earth_gravity.to_base_units().magnitude,
        dims=surface_geopotential.dims,
        coords=surface_geopotential.coords,
        attrs={'long_name': 'surface geopotential height',
               'units': 'meter'})

results in a difference in the xarray data array that is created (surface_height).  In the version using xarray 2022.6.0, the units from the constants.earth_gravity are appended to the array, which are then used by pint in the calculation of the layer_height in line 362 which in turn gives rise to the DimensionalityError.  

**Fix:**
======

use the **magnitude** of the **_constants.earth_gravity_** to avoid the units from being incorporated into the surface_height xarray data array:
       
      constants.earth_gravity.to_base_units().magnitude
    
This works for both the conda environment used for Python 3.8 and Python 3.7
