### ISSUE TITLE
perform_event_equalization dropping column in an empty dataframe 

### ISSUE THREAD

**Issue by bikegeek** [dtcenter/METcalcpy#238]
## Describe the Problem ##
While attempting to create a ROC diagram with the sample data:
[plot_20200507_074426.data.txt](https://github.com/dtcenter/METplotpy/files/9993476/plot_20200507_074426.data.txt)

and setting the **event_equal** to **True** in the custom config file, there is no matching data from performing the event equalization. When the following line is run (utils.perform_event_equalization):
output_ee_data = output_ee_data.drop('equalize', axis=1)

The following error is generated: 

_KeyError: "['equalize'] not found in axis"_

This is due to the output_ee_data data frame being an empty data frame.  

### Expected Behavior ###
*Provide a clear and concise description of what you expected to happen here.*

The following error is generated when using the custom_roc_diagram.yaml config file with event equalization turned on:

> Traceback (most recent call last):
>   File "/Volumes/d1/minnawin/feature_121_met_reformatter/METplotpy/metplotpy/plots/roc_diagram/roc_diagram.py", line 480, in <module>
>     main()
>   File "/Volumes/d1/minnawin/feature_121_met_reformatter/METplotpy/metplotpy/plots/roc_diagram/roc_diagram.py", line 469, in main
>     r = ROCDiagram(docs)
>   File "/Volumes/d1/minnawin/feature_121_met_reformatter/METplotpy/metplotpy/plots/roc_diagram/roc_diagram.py", line 82, in __init__
>     self.input_df = calc_util.perform_event_equalization(self.parameters, self.input_df)
>   File "/Volumes/d1/minnawin/feature_121_met_reformatter/METcalcpy/metcalcpy/util/utils.py", line 719, in perform_event_equalization
>     equalize_axis_data(fix_vals_keys, fix_vals_permuted_list, params, input_data, axis='1')
>   File "/Volumes/d1/minnawin/feature_121_met_reformatter/METcalcpy/metcalcpy/util/utils.py", line 689, in equalize_axis_data
>     return output_ee_data.drop('equalize', axis=1)
>   File "/Users/minnawin/miniconda/envs/mac_metplotpy_py38/lib/python3.8/site-packages/pandas/core/frame.py", line 4308, in drop
>     return super().drop(
>   File "/Users/minnawin/miniconda/envs/mac_metplotpy_py38/lib/python3.8/site-packages/pandas/core/generic.py", line 4153, in drop
>     obj = obj._drop_axis(labels, axis, level=level, errors=errors)
>   File "/Users/minnawin/miniconda/envs/mac_metplotpy_py38/lib/python3.8/site-packages/pandas/core/generic.py", line 4188, in _drop_axis
>     new_axis = axis.drop(labels, errors=errors)
>   File "/Users/minnawin/miniconda/envs/mac_metplotpy_py38/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5591, in drop
>     raise KeyError(f"{labels[mask]} not found in axis")
> KeyError: "['equalize'] not found in axis"

### Environment ###
Describe your runtime environment:
*1. Machine: (e.g. HPC name, Linux Workstation, Mac Laptop)* 
*2. OS: (e.g. RedHat Linux, MacOS)*MacOS
*3. Software version number(s)* Python 3.8.6, METplotpy 2.0 develop

### To Reproduce ###
Describe the steps to reproduce the behavior:

1.  Clone the METcalcpy repository and METplotpy repository in a working directory
2.  Set your PYTHONPATH: 

     path/to/METcalcpy:/path/to//METcalcpy/metcalcpy:/path/to/METplotpy:/path/to/METplotpy/metplotpy:/path/to/METplotpy/metplotpy/plots

    Replace path/to with the root/base directory where the METcalcpy and METplotpy code resides.

3. From the METplotpy/test/roc_diagram directory copy the following into your work space:

    custom_roc_diagram.yaml config file

    plot_20200507_074426.data or the CTC_ROC.data

4.  Generate the plot

     cd to your work space

        python $METPLOTPY_BASE/metplotpy/plots/roc_diagram ./custom_roc_diagram.yaml

Where METPLOTPY_BASE is the directory where the METplotpy and METcalcpy source code reside.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2702691

### Assignee ###
- [x] Select **engineer(s)** Minna Win
- [x] Select  **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Organization** level **Project** for support of the current coordinated release
- [ ] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by bikegeek** [comment]
replace this:
 
    output_ee_data = output_ee_data.drop('equalize', axis=1)

with this:

    try:
         output_ee_data = output_ee_data.drop('equalize', axis=1)

    except KeyError:
       pass

    return output_ee_data
